version: "3.9"
services:

  # Nginx Service
  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: yuba/nginx:v0.1
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www/html
      - ./nginx/logs:/var/log/nginx/
      - ./nginx/ssl:/etc/nginx/ssl/
    networks:
      - laravel_app
  
  # PHP Service
  app:
    build: 
      context: ./php/
      dockerfile: Dockerfile
    image: yuba/php-app:v0.1
    container_name: php-app
    restart: unless-stopped
    depends_on:
      - webserver
    tty: true
    volumes:
      - ./src:/var/www/html
    environment:
      APP_ENV: dev
    networks:
      - laravel_app

  # Composer from app service image
  composer:
    build:
      context: ./composer
      dockerfile: Dockerfile
    image: yuba/composer:v0.1
    container_name: composer-app
    depends_on:
      - app
    entrypoint: ['composer']
    volumes:
      - ./src:/var/www/html

  # Database Service
  database:
    build: 
      context: ./postgresql
      dockerfile: Dockerfile
    image: yuba/postgresql:v0.1
    container_name: postgresql-db
    restart: unless-stopped
    tty: true
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_PASSWORD: postgresql_password
      POSTGRES_USER: postgres
      POSTGRES_DB: laravel
    volumes: 
      - ./postgresql/postgres.conf:/usr/local/etc/postgres/postgres.conf
      - database-data:/var/lib/postgresql/data:delegated
    networks: 
      - laravel_app

  # Artisan CLI Service
  artisan:
    build:
      context: ./php
      dockerfile: Dockerfile
    image: yuba/artisan:v0.1
    container_name: artisan
    volumes:
      - ./src:/var/www/html
    depends_on:
      - database
    working_dir: /var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel_app

  # Node Package Manager Service
  npm:
    image: node:15-alpine3.10
    container_name: npm
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    entrypoint: ['npm']
    networks:
      - laravel_app

  # Redis Service
  redis:
    image: redis:6.2-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - laravel_app
  
# Define the network
networks:
  laravel_app:
    driver: bridge

# Define the volumes
volumes: 
  database-data:
    driver: local
    

