name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [webserver, app, database]

    steps:
      - uses: actions/checkout@v2
      - name: Build the docker image
        run: docker-compose build ${{ matrix.service }}
